### ISSUE TITLE
Recommend installing signed version by default for firefox

### ISSUE THREAD

**Issue by soredake** [FastForwardTeam/Website#30]
Most people are using stable firefox, and will try to install addon from site, and will fail cause by default site gives you an unsigned version. It will be better if site recommended installing signed version by default.

Examples bug reports:
https://github.com/FastForwardTeam/FastForward/issues/947
https://github.com/FastForwardTeam/FastForward/issues/971
https://github.com/FastForwardTeam/FastForward/issues/958

**Comment by AliahX** [comment]
done!
