### ISSUE TITLE
You can try out the (experimental) mv3 version here: https://nightly.link/FastForwardTeam/FastForward/workflows/main/manifest-v3

### ISSUE THREAD

**Issue by Asrum** [FastForwardTeam/Website#33]
You can try out the (experimental) mv3 version here: https://nightly.link/FastForwardTeam/FastForward/workflows/main/manifest-v3

_Originally posted by @NotAProton in https://github.com/FastForwardTeam/FastForward/issues/668#issuecomment-1495012926_

**Comment by BS-zombie** [comment]
MV3 is now our main version, so its not necessary to note this.
